name: flutter_adaptive_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
authors:
  - Alex Melnyk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
